sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD | cut -c 1-7)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project impactful-name-325819
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wandrewjam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wandrewjam/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
